### PR TITLE
feat(supported-version): add all kind

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/github-actions-magento2/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
I wasn't confident that the code I have in place for #35 actually supports every version out there. 

Fixes: N/A

## What is the new behavior?
As such, I've added a new kind to trial against ALL Magento versions.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ihor-sviziev — DISMISSED** [review]
Just one question - why do we need the `supported-version/dist/index.js` file?

**Comment by damienwebdev** [comment]
@ihor-sviziev I prefer writing in typescript, and Github's recommendation is to build to js and commit. see: https://github.com/actions/typescript-action

**Comment by ihor-sviziev** [comment]
Sorry, my question was about supported-version/src/kind/all.json

**Comment by damienwebdev** [comment]
@ihor-sviziev that was a miss on my part.

**Comment by damienwebdev** [comment]
The underlying bugs here are results of issues between the @mage-os mirror and upstream Magento.

The mirror is building from tags in the repo, whereas mainline Magento has packages tagged as one version, but published as another.

The main package the Adobe Stock Integration. See: https://github.com/magento/adobe-stock-integration/pull/1872

**Pull request merged**
